COLUMNS:
  gender: object
  age: float64
  hypertension: int64
  heart_disease: int64
  smoking_history: object
  bmi: float64
  HbA1c_level: float64
  blood_glucose_level: float64
  diabetes: int64

TARGET_COLUMN:
  name: diabetes